name: nlp-website
type: silverstripe
docroot: public
php_version: "8.5"
webserver_type: apache-fpm
xdebug_enabled: false
additional_fqdns: []
database:
    type: mariadb
    version: "10.11"
use_dns_when_possible: true
composer_version: "2"
web_environment: []
web_extra_exposed_ports:
    - name: vite
      container_port: 5173
      http_port: 5172
      https_port: 5173
corepack_enable: false
hooks:
    post-start:
        - exec: bash -c 'yarn'
        - exec: bash -c 'yarn build'
        - exec: bash -c 'composer install'
        - exec: bash -c 'sake dev/build'
